### PR TITLE
modifying log.info to log.error if exception occurs

### PR DESCRIPTION
**Pull request by hmaheswa**
This PR modifies log.info to log.error wherever it is present in ceph-qe-scripts to enable tfa analyser better classify errors.
logs: https://jenkins.ceph.redhat.com/view/RHCS%20QE/job/rhceph-test-executor/948/console

### CODE REVIEW

**Comment by vivekanandan-k-rh** [comment]
LGTM

**Review by anrao19 — APPROVED** [review]
LGTM

**Review by udaysk23 — APPROVED** [review]

**Review by ckulal — DISMISSED** [review]
lgtm

**Comment by mkasturi18** [comment]
@hmaheswa , can we have the pass logs attached

**Review by mkasturi18 — APPROVED** [review]
Attached logs simulate the exception

**Pull request merged**
