### PR TITLE
Changed indexless bucket verification command

### PR DESCRIPTION
**Pull request by udaysk23**
Changed indexless bucket verification command

Following is the log location of successful run:
http://pastebin.test.redhat.com/1061630
Signed-off-by: uday kurundwade <ukurundw@redhat.com>

### CODE REVIEW

**Review by viduship — APPROVED** [review]
looks good

**Comment by psathyan** [comment]
Please check with 5.2

**Review by anrao19 — APPROVED** [review]

**Review by ckulal — COMMENTED** [review]
LGTM

**Comment by udaysk23** [comment]
> Please check with 5.2

Following is the log location of successful run on 5.x cluster:
http://pastebin.test.redhat.com/1061794

**Comment by udaysk23** [comment]
> Please check with 5.2

Following is the log location of successful run on 5.2 cluster:
http://pastebin.test.redhat.com/1061983

**Review by mkasturi18 — APPROVED** [review]

**Pull request merged**
