### PR TITLE
Increase the sync lease to 1200 seconds for 0 shards sync test

### PR DESCRIPTION
**Pull request by viduship**
Passed log: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-Y2H8HK/

### CODE REVIEW

**Comment by ckulal** [comment]
Hi @viduship ,
In a log provided, lease period is still in 120sec,
Wait for the sync lease period of 120 seconds'

**Comment by viduship** [comment]
> Hi @viduship , In a log provided, lease period is still in 120sec, Wait for the sync lease period of 120 seconds'

yeah, that message was changed later, after the run. 

please also note the execution time in the logs for a test which is 46 minutes (including the 1200 seconds sleep time.)
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-MV1UXH/

I am triggering a new log, that displays correct message related to the ssync lease period

**Comment by viduship** [comment]
@ckulal , new passed log with the correct message for sync lease period http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-Y2H8HK/

**Comment by ckulal** [comment]
> @ckulal , new passed log with the correct message for sync lease period http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-Y2H8HK/

Hi @viduship , small doubt, here I could see conf dump for rgw_sync_lease_period as 120
{"section":"client.rgw.shared.pri","name":"rgw_sync_lease_period","value":"120","level":"dev","can_update_at_runtime":true,"mask":""},


what is this value represents?

**Review by mkasturi18 — APPROVED** [review]

**Pull request merged**
