### PR TITLE
[T2-Automation][CEPH-83575407]:Bucket Notifications Using SASL SCRAM

### PR DESCRIPTION
**Pull request by hmaheswa**
This PR is to automate kafka sasl scram testing.
installation and configuration of security types are present in the cephci PR: https://github.com/red-hat-storage/cephci/pull/2204
hotfix bz: [Bz 2160209](https://bugzilla.redhat.com/show_bug.cgi?id=2160209)
polarion id: [CEPH-83575407](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83575407)
reducing objects_count to 10 because the configs count is huge
pacific pass logs:

1. tier-2_rgw_test-bucket-notifications-kafka-ssl.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-t4ix2/
2. tier-2_rgw_test-bucket-notifications-kafka-sasl-sanity.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-byvu0/
3. tier-2_rgw_test-bucket-notifications-kafka-sasl-scheduled.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-o4cwm
4. tier-2_rgw_test-bucket-notifications.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-sucsk/

quincy pass logs: (failures are known issues for multipart events)

1. tier-2_rgw_test-bucket-notifications-kafka-ssl.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-vg727
2. tier-2_rgw_test-bucket-notifications-kafka-sasl-sanity.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-i90gk/
3. tier-2_rgw_test-bucket-notifications-kafka-sasl-scheduled.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-99e2z/
4. tier-2_rgw_test_bucket_notifications.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-pfktn/

### CODE REVIEW

**Comment by viduship** [comment]
> This PR is to automate kafka sasl scram testing. installation and configuration of security types are present in the cephci PR: [red-hat-storage/cephci#2204](https://github.com/red-hat-storage/cephci/pull/2204) hotfix bz: [Bz 2160209](https://bugzilla.redhat.com/show_bug.cgi?id=2160209) polarion id: [CEPH-83575407](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83575407) reducing objects_count to 10 because the configs are huge pacific pass logs:
> 
> 1. tier-2_rgw_test-bucket-notifications-kafka-ssl.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-t4ix2/
> 2. tier-2_rgw_test-bucket-notifications-kafka-sasl-sanity.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-byvu0/
> 3. tier-2_rgw_test-bucket-notifications-kafka-sasl-scheduled.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-o4cwm
> 4. tier-2_rgw_test-bucket-notifications.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-sucsk/

@hmaheswa , Is also supported on Quincy, can we have at least one Quincy log too?

**Comment by hmaheswa** [comment]
> > This PR is to automate kafka sasl scram testing. installation and configuration of security types are present in the cephci PR: [red-hat-storage/cephci#2204](https://github.com/red-hat-storage/cephci/pull/2204) hotfix bz: [Bz 2160209](https://bugzilla.redhat.com/show_bug.cgi?id=2160209) polarion id: [CEPH-83575407](https://polarion.engineering.redhat.com/polarion/#/project/CEPH/workitem?id=CEPH-83575407) reducing objects_count to 10 because the configs are huge pacific pass logs:
> > 
> > 1. tier-2_rgw_test-bucket-notifications-kafka-ssl.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-t4ix2/
> > 2. tier-2_rgw_test-bucket-notifications-kafka-sasl-sanity.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-byvu0/
> > 3. tier-2_rgw_test-bucket-notifications-kafka-sasl-scheduled.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-o4cwm
> > 4. tier-2_rgw_test-bucket-notifications.yaml: http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-sucsk/
> 
> @hmaheswa , Is also supported on Quincy, can we have at least one Quincy log too?

Done @viduship

**Review by ckulal — COMMENTED** [review]
Looks good,

**Review by mkasturi18 — APPROVED** [review]
Requested changes are implemented. The changes look good.

**Pull request merged**
