### PR TITLE
Add test on indexless(blind) buckets

### PR DESCRIPTION
**Pull request by mkasturi18**
Add test on s3 operations on indexless buckets

### CODE REVIEW

**Comment by mkasturi18** [comment]
PFA logs at http://magna002.ceph.redhat.com/ceph-qe-logs/madhavi/PRs/indexless/PR109/

**Comment by rakeshgm** [comment]
looks good.

**Comment by rakeshgm** [comment]
you need to add this in cephci too once this is merged and also to update polarion.

**Review by rakeshgm — DISMISSED** [review]

**Comment by mkasturi18** [comment]
Sure, will have them added to cephci and update polarion too.

**Comment by rakeshgm** [comment]
I forgot to request one small change. I think validating the commands after reverting to default placement group should also be done.

**Comment by mkasturi18** [comment]
Thanks Rakesh, have added the validation on revert to default placement group.

logs at http://magna002.ceph.redhat.com/ceph-qe-logs/madhavi/PRs/indexless/PR109/pacific_console.log

**Review by rakeshgm — APPROVED** [review]

**Pull request merged**
